/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvgui;

import javax.swing.JOptionPane;

/**
 *
 * @author Aco PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalInfoButton = new javax.swing.JButton();
        workExperienceButton = new javax.swing.JButton();
        educationButton = new javax.swing.JButton();
        skillComboBox = new javax.swing.JComboBox<>();
        appInfoButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setTitle("CV Application");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.GridLayout(6, 1, 1, 0));

        personalInfoButton.setText("Personal Info");
        personalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(personalInfoButton);

        workExperienceButton.setText("Work Experience");
        workExperienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workExperienceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(workExperienceButton);

        educationButton.setText("Education");
        educationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(educationButton);

        skillComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Communication skills", "Organizational/Menagerial skills", "Speciality knowledge", "PC skills", "Programming knowledge" }));
        skillComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(skillComboBox);

        appInfoButton.setText("Application Info");
        appInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(appInfoButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfoButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Name: Aleksandar Stojanovic\nEmail: 1plsdontsapmme@gmail.com\n"
                + "Address: Cara Dusana Doboj, Bosnia and Herzegovina\n"
                + "Phone number: 0038765***900", "PERSONAL INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_personalInfoButtonActionPerformed

    private void workExperienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workExperienceButtonActionPerformed
        JOptionPane.showMessageDialog(this, "01.06.2017 - Present: Vice chief Accountant in international company.\n"
                + "21.11.2016 - 03.05.2017: Bar Owner/Manager.\n"
                + "03.10.2013 - 15.06.2016: Proffesional translator of ducments and scientific papaers.", "WORK EXPERIENCE", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_workExperienceButtonActionPerformed

    private void educationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationButtonActionPerformed
        JOptionPane.showMessageDialog(this, "30.10.2013 - 06.09.2016: Master of Arts in English Language and Literature\n"
                + "08.07.2019 - 18.06.2013: Bachelor of Arts in English Language and Literature\n"
                + "02.09.2005 - 15.06.2009: Economics technician", "EDUCATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_educationButtonActionPerformed

    private void skillComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillComboBoxActionPerformed
        if (skillComboBox.getSelectedItem().toString() == "Communication skills") {
            JOptionPane.showMessageDialog(this, "Advanced skills in communication with:\n"
                    + "Superiors/Colleagues/Customers/Partners\n"
                    + "Advanced business communication skills including:\n"
                    + "Negotiation/Ordering/Advising/Consulting/Presentation", "COMMUNICATION SKILLS", JOptionPane.INFORMATION_MESSAGE);
        }
        if (skillComboBox.getSelectedItem().toString() == "Organizational/Menagerial skills") {
            JOptionPane.showMessageDialog(this, "Department organization:\n"
                    + "Organizing shifts/Vacation planning/Bonuses (rewards)/Staff requirements\n"
                    + "Employee evaluations/Monitoring/Correcting/Training employees/Task prioritization", "ORGANISATIONAL/MANAGERIAL SKILLS", JOptionPane.INFORMATION_MESSAGE);
        }
        if (skillComboBox.getSelectedItem().toString() == "Speciality knowledge") {
            JOptionPane.showMessageDialog(this, "Accounting/Finance/Management\n"
                    + "PERSONAL TRAITS:\n"
                    + "Precise/Hardworking/Responsible/Reliable/Determined/Great pressure handling", "SPECIALITY KNOWLEDGE", JOptionPane.INFORMATION_MESSAGE);
        }
        if (skillComboBox.getSelectedItem().toString() == "PC skills") {
            JOptionPane.showMessageDialog(this, "Expert knowledge of Microsoft Office(Office Libre)\n"
                    + "Expert knowledge of Excel (Formulas, LOOKUP, conditioning)\n"
                    + "Expert knowledge of Diamant 3.0 accounting software(OfficialTraining&Experience)\n"
                    + "User knowledge of Linux OS", "PC SKILLS", JOptionPane.INFORMATION_MESSAGE);
        }
        if (skillComboBox.getSelectedItem().toString() == "Programming knowledge") {
            JOptionPane.showMessageDialog(this, "Good knowledge of Java(Swing,SceneBuilder)(Actively Learning)\n"
                    + "Understanding of MySql(Actively Learning)\n"
                    + "Work experience with Scrum tool 'Jira'\n"
                    + "User knowledge of Git\n"
                    + "JavaScript(Getting familiar with basics)", "PROGRAMMING KNOWLEDGE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_skillComboBoxActionPerformed

    private void appInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appInfoButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Display of personal information in this application is without much detail"
                + " in order to avoid missue of my private information.\n"
                + "However basic this app may be, it is 100% designed coded and developed"
                + " by Aleksandar Stojanovc with purpose of learning and practicing Java code.\n"
                + "Thank you for using it and respecting my prive information.", "ABOUT APPLICATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_appInfoButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appInfoButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton educationButton;
    private javax.swing.JButton personalInfoButton;
    private javax.swing.JComboBox<String> skillComboBox;
    private javax.swing.JButton workExperienceButton;
    // End of variables declaration//GEN-END:variables
}
